/*
Copyright 2026 MicroEJ Corp. All rights reserved.
Use of this source code is governed by a BSD-style license that can be found with this software
*/
package com.microej.example.navigationframework;


import com.microej.example.navigationframework.navigation.ExamplePageFactory;
import com.microej.example.navigationframework.navigation.Pages;
import com.microej.example.navigationframework.widget.VectorCheckBox;
import com.microej.example.navigationframework.widget.VectorRadioButton;
import com.microej.example.navigationframework.widget.VectorImageButton;
import com.microej.example.navigationframework.widget.VectorImageWidget;
import com.microej.example.navigationframework.widget.VectorLabel;
import ej.microui.MicroUI;
import ej.microui.display.Colors;
import ej.microvg.VectorFont;
import ej.mwt.Desktop;
import ej.mwt.style.EditableStyle;
import ej.mwt.style.background.NoBackground;
import ej.mwt.style.background.RectangularBackground;
import ej.mwt.style.dimension.OptimalDimension;
import ej.mwt.style.outline.FlexibleOutline;
import ej.mwt.style.outline.UniformOutline;
import ej.mwt.style.outline.border.RoundedBorder;
import ej.mwt.stylesheet.Stylesheet;
import ej.mwt.stylesheet.cascading.CascadingStylesheet;
import ej.mwt.stylesheet.selector.ClassSelector;
import ej.mwt.stylesheet.selector.OddChildSelector;
import ej.mwt.stylesheet.selector.TypeSelector;
import ej.mwt.stylesheet.selector.combinator.AndCombinator;
import ej.mwt.util.Alignment;
import ej.navigation.Navigator;
import ej.widget.container.List;

/**
 * Generated by the application template.
 *
 * Please keep it in sync with the property 'applicationEntryPoint' defined in build.gradle.kts.
 */
public class Main {

    public static final int CS_SPLASH = 0;
    public static final int CS_ROOT = 1;
    public static final int CS_HOME_TITLE = 2;
    public static final int CS_CENTER_WIDGET = 3;
    public static final int CS_LIST_ITEM = 4;
    public static final int CS_BUTTON = 5;
    public static final int CS_TITLE = 6;

    private static final int CONCRETE_B75 = 0x262a2c;
    private static final int CONCRETE_B50 = 0x4b5357;
    public static final int CORAL = 0xee502e;
    private static final String REGULAR_FONT_PATH = "/fonts/SourceSansPro-Regular.ttf";
    private static final String BOLD_FONT_PATH = "/fonts/SourceSansPro-Bold.ttf";

    private Desktop desktop;

    public static void main(String[] args) {
        new Main();
    }

    private Main() {
        MicroUI.start();

        this.desktop = new Desktop();
        this.desktop.setStylesheet(this.buildStylesheet());

        Navigator.initialize(this.desktop, new ExamplePageFactory());
        Navigator.getInstance().navigateTo(Pages.SPLASH);
    }

    private Stylesheet buildStylesheet() {
        CascadingStylesheet stylesheet = new CascadingStylesheet();

        // default
        EditableStyle style = stylesheet.getDefaultStyle();
        style.setBackground(NoBackground.NO_BACKGROUND);
        style.setColor(Colors.WHITE);

        // type selectors
        style = stylesheet.getSelectorStyle(new TypeSelector(VectorImageButton.class));
        style.setDimension(OptimalDimension.OPTIMAL_DIMENSION_XY);
        style.setBorder(new RoundedBorder(Colors.WHITE, 16, 5));
        style.setMargin(new UniformOutline(20));

        style = stylesheet.getSelectorStyle(new TypeSelector(VectorLabel.class));
        style.setExtraObject(VectorLabel.FONT_FIELD, VectorFont.loadFont(REGULAR_FONT_PATH));
        style.setExtraObject(VectorLabel.FONT_SIZE_FIELD, 32);
        style.setVerticalAlignment(Alignment.VCENTER);
        style.setPadding(new UniformOutline(20));

        style = stylesheet.getSelectorStyle(new TypeSelector(VectorImageWidget.class));
        style.setHorizontalAlignment(Alignment.HCENTER);
        style.setVerticalAlignment(Alignment.VCENTER);

        style = stylesheet.getSelectorStyle(new TypeSelector(VectorCheckBox.class));
        style.setExtraObject(VectorLabel.FONT_FIELD, VectorFont.loadFont(REGULAR_FONT_PATH));
        style.setExtraObject(VectorLabel.FONT_SIZE_FIELD, 32);
        style.setVerticalAlignment(Alignment.VCENTER);
        style.setExtraInt(VectorCheckBox.CHECKED_COLOR_FIELD, CORAL);
        style.setMargin(new FlexibleOutline(2, 0, 2, 0));

        style = stylesheet.getSelectorStyle(new TypeSelector(VectorRadioButton.class));
        style.setExtraObject(VectorLabel.FONT_FIELD, VectorFont.loadFont(REGULAR_FONT_PATH));
        style.setExtraObject(VectorLabel.FONT_SIZE_FIELD, 32);
        style.setVerticalAlignment(Alignment.VCENTER);
        style.setExtraInt(VectorCheckBox.CHECKED_COLOR_FIELD, CORAL);
        style.setMargin(new FlexibleOutline(2, 0, 2, 0));

        style = stylesheet.getSelectorStyle(new TypeSelector(List.class));
        style.setDimension(OptimalDimension.OPTIMAL_DIMENSION_Y);

        // class selectors
        style = stylesheet.getSelectorStyle(new ClassSelector(CS_SPLASH));
        style.setBackground(new RectangularBackground(Colors.BLACK));

        style = stylesheet.getSelectorStyle(new ClassSelector(CS_ROOT));
        style.setBackground(new RectangularBackground(CONCRETE_B75));

        style = stylesheet.getSelectorStyle(new ClassSelector(CS_HOME_TITLE));
        style.setBackground(new RectangularBackground(CORAL));
        style.setHorizontalAlignment(Alignment.HCENTER);
        style.setExtraObject(VectorLabel.FONT_FIELD, VectorFont.loadFont(BOLD_FONT_PATH));

        style = stylesheet.getSelectorStyle(new ClassSelector(CS_TITLE));
        style.setExtraObject(VectorLabel.FONT_FIELD, VectorFont.loadFont(BOLD_FONT_PATH));

        style = stylesheet.getSelectorStyle(new ClassSelector(CS_CENTER_WIDGET));
        style.setMargin(new FlexibleOutline(20, 20, 0, 20));

        style = stylesheet.getSelectorStyle(new ClassSelector(CS_LIST_ITEM));
        style.setBackground(new RectangularBackground(CONCRETE_B50));

        style = stylesheet.getSelectorStyle(
                new AndCombinator(new ClassSelector(CS_LIST_ITEM), OddChildSelector.ODD_CHILD_SELECTOR));
        style.setBackground(new RectangularBackground(CONCRETE_B75));

        style = stylesheet.getSelectorStyle(new ClassSelector(CS_BUTTON));
        style.setDimension(OptimalDimension.OPTIMAL_DIMENSION_XY);
        style.setBackground(new RectangularBackground(CORAL));
        style.setHorizontalAlignment(Alignment.HCENTER);
        style.setPadding(new FlexibleOutline(8, 64, 8, 64));
        style.setMargin(new FlexibleOutline(20, 0, 20, 0));

        return stylesheet;
    }

}